### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by balduser** [vmxdev/xenoeye#1]
Прошу помощи с установкой вашего продукта на CentOS8. Релиз 8.2.2004, скачал на днях
Пробую установить с github. Скачиваю командой `git clone https://github.com/vmxdev/xenoeye.git`
Вроде проходит без ошибок. Пытаюсь установить по инструкции с этого сайта: http://xenoeye.com/cgi-bin/fossil.cgi/wiki?name=Compiling+and+installing+Xenoeye
Установил следующее:
_(1/4): autoconf-2.69-27.el8.noarch.rpm                                                                                                                                                                       708 kB/s | 710 kB     00:01
(2/4): libtool-2.4.6-25.el8.x86_64.rpm                                                                                                                                                                       692 kB/s | 709 kB     00:01
(3/4): automake-1.16.1-6.el8.noarch.rpm                                                                                                                                                                      668 kB/s | 713 kB     00:01
(4/4): perl-Thread-Queue-3.13-1.el8.noarch.rpm_

Делаю
_[root@centos ~ ]# cd xenoeye
[root@centos xenoeye]# autoreconf --install
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:9: installing './ar-lib'
configure.ac:9: installing './compile'
configure.ac:13: installing './config.guess'
configure.ac:13: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'_

Затем пытаюсь подготовиться к сборке
_[root@centos xenoeye]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether compiler understands -Wall -Wextra -pedantic... yes
checking for library containing pcap_open_live... no
configure: error: unable to find the pcap_open_live() function_

Ошибка, и дальше не идёт
_[root@centos xenoeye]# make
make: *** No targets specified and no makefile found.  Stop._

Я не специалист в линуксе, поэтому был бы благодарен за подробное объяснение, что я делаю не так.

**Comment by balduser** [comment]
Также пробовал скачивать zip с вашего сайта: http://xenoeye.com/cgi-bin/fossil.cgi/info/70267f7d5d7f5101
Распаковал на centos в папку xenoeye-f
_[root@centos xenoeye-f]# autoreconf --install
configure.ac:5: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:5: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1_

Ну и дальше конечно ничего не идёт
_[root@centos xenoeye-f]# ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
[root@centos xenoeye-f]# make
make: *** No targets specified and no makefile found.  Stop._

**Comment by vmxdev** [comment]
Сейчас на сайте и на гитхабе лежит совершенно разный код. На сайте старая версия, умеет только Netflow v5 и вообще морально устарела.

Здесь, на гитхабе, заново написанный коллектор, он умеет Netflow v9 и IPFIX, но пока он ни для чего не пригоден, на нем проводятся разные эксперименты.

Думаю, можно собрать тот код, который с сайта, нужно просто доустановить какие-нибудь пакеты (похоже, не хватает чего-то связанного с gettext).

Вам может быть будет проще поискать другой коллектор, старую версию нашего коллектора никто уже реанимировать и исправлять не будет

**Comment by balduser** [comment]
Спасибо за оперативный ответ. В таком случае у меня 2 вопроса:
1) Способ, которым я пытался установить код с гитхаба - `autoreconf --install`, затем `./configure` - он правильный, или я что-то пропустил?
2) По скриншотам версия с вашего сайта меня бы устроила. Подскажите хотябы, на какой системе её лучше запустить, всё равно я пока экспериментирую в виртуалке.

**Comment by vmxdev** [comment]
> Способ, которым я пытался установить код с гитхаба - autoreconf --install, затем ./configure - он правильный, или я что-то пропустил?

Да, все верно. Нужно только доустановить библиотеку pcap (libpcap-devel). Она используется для довольно экзотических случаев - чтобы снимать netflow прямо с интерфейса (например, с зеркала) или чтобы коллектор захватывал netflow из дампа трафика.

> на какой системе её лучше запустить

Попробуйте на вашем Centos, может быть получится. Возможно, если доустановить gettext-devel он и соберется. Берите вот этот код http://xenoeye.com/cgi-bin/fossil.cgi/tarball/Xenoeye-ef9d64ac8e.tar.gz , он должен быть рабочий. В последних коммитах что-то сломали

**Comment by balduser** [comment]
Установил пакеты: gettext-devel `yum install gettext-devel` и libpcap-devel `dnf --enablerepo=PowerTools install libpcap-devel`, после чего даже получилось в папке кода с гитхаба сделать `./configure`, но `make` выдал ошибку:

_[root@centos xenoeye]# make
make  all-am
make[1]: Entering directory '/root/xenoeye'
  CC       xenoeye.o
xenoeye.c:34:10: fatal error: aajson/aajson.h: No such file or directory
 #include "aajson/aajson.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:714: xenoeye.o] Error 1
make[1]: Leaving directory '/root/xenoeye'
make: *** [Makefile:553: all] Error 2_

Версию из вашей ссылки попробую попозже.

**Comment by vmxdev** [comment]
После git clone нужно инициализировать "подмодули".  Что-то вроде
```
$ git clone https://github.com/vmxdev/xenoeye/
$ cd xenoeye
$ git submodule update --init --recursive
$ autoreconf -i
$ ./configure && make
```
Команды сборки можно посмотреть в логе Травис, если щелкнуть по серо-зеленой кнопке `build | passing` - https://travis-ci.org/vmxdev/xenoeye

В этой версии, которая на гитхабе, для пользователей нет вообще ничего интересного. Он сейчас просто захватывает и парсит netflow-пакеты
